#!/bin/bash
export AUTO_DIR="$HOME/auto"
export AUTO_SETTINGS_DIR="$AUTO_DIR/settings"
if [[ $PATH != *"auto/path"* ]]; then
    PATH=$PATH:~/auto/path
fi



for filename in $(ls /home/paolo/auto/source/*); do 
    source $filename
done


PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
